# services:
#   web:
#     build: .
#     ports:
#       - "80:80"
#     environment:
#       NODE_ENV: production

services:
  web:
    image: shaibenmichael/mpathic-family-frontend-web:latest
    ports:
      - "80:80"